spring.application.name=CrudOperation
server.port=8088

#  http://localhost:8088/h2-console
# H2 Db configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:db
spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.username=admin_viewer
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always